# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameEdit)
        self.roastLevelEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roastLevelEdit.setObjectName("roastLevelEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.roastLevelEdit)
        self.groundOrBeansEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.groundOrBeansEdit.setObjectName("groundOrBeansEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.groundOrBeansEdit)
        self.tasteDescriptionEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.tasteDescriptionEdit.setObjectName("tasteDescriptionEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.tasteDescriptionEdit)
        self.priceEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceEdit.setObjectName("priceEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priceEdit)
        self.packagingSizeEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.packagingSizeEdit.setObjectName("packagingSizeEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.packagingSizeEdit)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.nameEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.roastLevelEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Степень обжарки"))
        self.groundOrBeansEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Молотый/в зернах"))
        self.tasteDescriptionEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.priceEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Цена"))
        self.packagingSizeEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Объем упаковки"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
